---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name:  Install counting panda
  hosts: base
  become: yes
  tags: counting
  roles:
    - { role: counting-panda }

- name:  Install static panda
  hosts: base
  become: yes
  tags: static
  roles:
    - { role: static-panda }
